### PR TITLE
Remove references to 'start' and `stop`

### PR DESCRIPTION
**Pull request by fatty1380**
The documentation here steered me wrong as I implemented activate/deactivate functionality in my app based around a `configure`, `start` and `stop` methods as written up in the README. I've updated to explain the methods on the `BackgroundFetch` object, and also explain the object properties available.

Hope this will help anyone else who comes along!
Pat

### CODE REVIEW

**Comment by christocracy** [comment]
Can't accept this.  You misunderstand the purpose of #finish.  This is a signal to iOS that "my callback has completed.  You may finish the fetch operation".

iOS provides exactly 30s of bg time during a fetch event.  #finish is the signal that you're done with your 30s of allotted time

**Comment by christocracy** [comment]
Under no circumstances will I accept the removal of #start, #stop methods

**Comment by fatty1380** [comment]
I'm just looking at the source. There is no "start" or "stop" method on the `window.BackgroundFetch` object

**Comment by fatty1380** [comment]
... and yes, I did misunderstand the purpose of `finish`. Thanks for clearing that up

**Pull request closed without merging**
