### PR TITLE
Add package.json so we can use via NPM

### PR DESCRIPTION
**Pull request by mikeljames**
Added npm package.json, fancy hosting on npm? Join the other plugins?

### CODE REVIEW

**Comment by christocracy** [comment]
You're paying npm for a private account?
https://www.npmjs.com/private-modules

You can't publish this to a public npm package.

On Tuesday, December 15, 2015, Mike James <notifications@github.com> wrote:

> Added npm package.json, fancy hosting on npm? Join the other plugins?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/christocracy/cordova-plugin-background-fetch/pull/24
> Commit Summary
>
>    - Add package.json so we can use via NPM
>
> File Changes
>
>    - *A* package.json
>    <https://github.com/christocracy/cordova-plugin-background-fetch/pull/24/files#diff-0>
>    (21)
>
> Patch Links:
>
>    -
>    https://github.com/christocracy/cordova-plugin-background-fetch/pull/24.patch
>    -
>    https://github.com/christocracy/cordova-plugin-background-fetch/pull/24.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/pull/24>.
>


-- 
Snet form Gmail Mobile

**Comment by mikeljames** [comment]
Why does it need to be private?

**Comment by christocracy** [comment]
Oh, sorry.  I thought I was commenting on one of my private-repo projects.  I see this is my public `background-fetch` project, so ignore what I said.

**Comment by christocracy** [comment]
Is this you on npm, pebblecode?  you should add me as a collaboration so I can publish my own plugin.

**Comment by mikeljames** [comment]
sure go ahead setup an npmjs.org account, login with the CLI and run npm publish in the directory of the latest changes of the project. I'm unpublishing our one.

**Comment by mikeljames** [comment]
Hi, So I've gone ahead an unpublished https://www.npmjs.com/package/cordova-plugin-background-fetch I'm going to publish the fork under a different name so this doesn't block me. When you get the chance of publishing I'll remove the fork :)

**Pull request merged**
